# Generated by Django 2.2.13 on 2020-10-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadAndReplyNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.PositiveIntegerField(default=0, editable=False, verbose_name='阅读数')),
                ('reply_num', models.PositiveIntegerField(default=0, editable=False, verbose_name='回复数')),
                ('main_floor_num', models.PositiveIntegerField(default=0, editable=False, verbose_name='主楼数')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '阅读和回复数',
                'verbose_name_plural': '阅读和回复数',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '点赞数',
                'verbose_name_plural': '点赞数',
            },
        ),
        migrations.CreateModel(
            name='LikeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True, verbose_name='点赞用户ID')),
                ('platform', models.CharField(max_length=10, null=True, verbose_name='平台')),
                ('is_liked', models.BooleanField(default=False, verbose_name='是否点赞')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='readAndReplyNumAndLikes.Likes')),
            ],
            options={
                'verbose_name': '点赞细节',
                'verbose_name_plural': '点赞细节',
            },
        ),
    ]
