# Generated by Django 2.2.10 on 2020-03-20 08:05

from django.db import migrations, models
import django.db.models.deletion
import transaction.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yonghu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='标题')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('status', models.PositiveIntegerField(choices=[(0, '待处理'), (1, '已完成')], verbose_name='状态')),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedbacks', to='yonghu.Yonghu')),
            ],
            bases=(models.Model, transaction.models.GetImagePath),
        ),
    ]
