# Generated by Django 2.2.10 on 2020-03-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '用户反馈', 'verbose_name_plural': '用户反馈'},
        ),
    ]
