# Generated by Django 2.2.13 on 2020-10-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200321_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='yonghu',
        ),
        migrations.AddField(
            model_name='feedback',
            name='platform',
            field=models.CharField(max_length=10, null=True, verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.CharField(max_length=255, null=True, verbose_name='点赞用户ID'),
        ),
    ]
