# Generated by Django 2.2.10 on 2020-04-19 20:04

from django.db import migrations, models
import django.db.models.deletion
import images.getImagePath
import readAndReplyNum.getReadAndReplyNum


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0003_auto_20200405_0044'),
        ('Messages', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonghu.Yonghu', verbose_name='发帖人')),
            ],
            options={
                'verbose_name': '发表帖子',
                'verbose_name_plural': '发表帖子',
                'ordering': ['-created_time'],
            },
            bases=(models.Model, readAndReplyNum.getReadAndReplyNum.GetReadAndReplyNum, images.getImagePath.GetImagePath),
        ),
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Messages.Message')),
            ],
            bases=('Messages.message', models.Model),
        ),
        migrations.DeleteModel(
            name='huifu',
        ),
        migrations.DeleteModel(
            name='tiezi',
        ),
    ]
