# Generated by Django 2.2.10 on 2020-04-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200420_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15, verbose_name='类型')),
            ],
            options={
                'verbose_name': '帖子类型',
                'verbose_name_plural': '帖子类型',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='yonghu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yonghu.Yonghu', verbose_name='发帖人'),
        ),
        migrations.DeleteModel(
            name='PostMessage',
        ),
    ]
