# Generated by Django 2.2.13 on 2020-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0, verbose_name='性别')),
                ('country', models.CharField(default='', max_length=16, verbose_name='国家')),
                ('province', models.CharField(default='', max_length=32, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=16, verbose_name='城市')),
                ('avatarUrl', models.URLField(blank=True, default='', null=True, verbose_name='头像地址')),
                ('is_auth', models.BooleanField(default=False, verbose_name='是否认证')),
                ('is_auth_new', models.BooleanField(default=False, verbose_name='是否认证(新系统)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='电话号码')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
            options={
                'verbose_name': 'APP用户',
                'verbose_name_plural': 'APP用户',
            },
        ),
        migrations.CreateModel(
            name='NewUSCINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=16, null=True, unique=True, verbose_name='校园网用户名')),
                ('Password', models.CharField(max_length=32, null=True, verbose_name='校园网密码')),
                ('QQUser', models.CharField(db_index=True, max_length=255, null=True, verbose_name='QQ用户ID')),
                ('WXUser', models.CharField(db_index=True, max_length=255, null=True, verbose_name='微信用户ID')),
                ('APPUser', models.CharField(db_index=True, max_length=255, null=True, verbose_name='APP用户ID')),
            ],
            options={
                'verbose_name': '南华大学新版教务在线用户信息',
                'verbose_name_plural': '南华大学新版教务在线用户信息',
            },
        ),
        migrations.CreateModel(
            name='QQUser',
            fields=[
                ('nickName', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0, verbose_name='性别')),
                ('country', models.CharField(default='', max_length=16, verbose_name='国家')),
                ('province', models.CharField(default='', max_length=32, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=16, verbose_name='城市')),
                ('avatarUrl', models.URLField(blank=True, default='', null=True, verbose_name='头像地址')),
                ('is_auth', models.BooleanField(default=False, verbose_name='是否认证')),
                ('is_auth_new', models.BooleanField(default=False, verbose_name='是否认证(新系统)')),
                ('openid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'QQ用户',
                'verbose_name_plural': 'QQ用户',
            },
        ),
        migrations.CreateModel(
            name='UscInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=16, null=True, unique=True, verbose_name='校园网用户名')),
                ('Password', models.CharField(max_length=32, null=True, verbose_name='校园网密码')),
                ('QQUser', models.CharField(db_index=True, max_length=255, null=True, verbose_name='QQ用户ID')),
                ('WXUser', models.CharField(db_index=True, max_length=255, null=True, verbose_name='微信用户ID')),
                ('APPUser', models.CharField(db_index=True, max_length=255, null=True, verbose_name='APP用户ID')),
            ],
            options={
                'verbose_name': '南华大学教务在线用户信息',
                'verbose_name_plural': '南华大学教务在线用户信息',
            },
        ),
        migrations.CreateModel(
            name='WXUser',
            fields=[
                ('nickName', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0, verbose_name='性别')),
                ('country', models.CharField(default='', max_length=16, verbose_name='国家')),
                ('province', models.CharField(default='', max_length=32, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=16, verbose_name='城市')),
                ('avatarUrl', models.URLField(blank=True, default='', null=True, verbose_name='头像地址')),
                ('is_auth', models.BooleanField(default=False, verbose_name='是否认证')),
                ('is_auth_new', models.BooleanField(default=False, verbose_name='是否认证(新系统)')),
                ('openid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
            },
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['email'], name='yonghu_appu_email_a55ff0_idx'),
        ),
    ]
