# Generated by Django 2.0.6 on 2019-11-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UscInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=16, null=True, unique=True, verbose_name='校园网用户名')),
                ('Password', models.CharField(max_length=32, null=True, verbose_name='校园网密码')),
            ],
            options={
                'verbose_name': '南华大学教务在线用户信息',
                'verbose_name_plural': '南华大学教务在线用户信息',
            },
        ),
        migrations.CreateModel(
            name='Yonghu',
            fields=[
                ('openid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('nickName', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0, verbose_name='性别')),
                ('country', models.CharField(default='', max_length=16, verbose_name='国家')),
                ('province', models.CharField(default='', max_length=32, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=16, verbose_name='城市')),
                ('avatarUrl', models.URLField(blank=True, default='', null=True, verbose_name='头像地址')),
                ('is_auth', models.BooleanField(default=False, verbose_name='是否认证')),
            ],
        ),
        migrations.AddField(
            model_name='uscinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usc', to='yonghu.Yonghu', verbose_name='所关联用户'),
        ),
    ]
