# Generated by Django 2.2.10 on 2020-04-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yonghu',
            options={'verbose_name': '南华大学教务在线用户信息', 'verbose_name_plural': '南华大学教务在线用户信息'},
        ),
    ]
