# Generated by Django 2.0.6 on 2020-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uscinfo',
            name='systemVersion',
            field=models.IntegerField(choices=[(0, '老系统'), (1, '新系统')], default=0, verbose_name='系统版本'),
        ),
    ]
