# Generated by Django 2.0.6 on 2019-11-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0002_auto_20191123_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
