# Generated by Django 2.0.6 on 2020-02-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0002_uscinfo_systemversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUSCINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=16, null=True, unique=True, verbose_name='校园网用户名')),
                ('Password', models.CharField(max_length=32, null=True, verbose_name='校园网密码')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uscNew', to='yonghu.Yonghu', verbose_name='所关联用户')),
            ],
            options={
                'verbose_name': '南华大学新版教务在线用户信息',
                'verbose_name_plural': '南华大学新版教务在线用户信息',
            },
        ),
        migrations.RemoveField(
            model_name='uscinfo',
            name='systemVersion',
        ),
    ]
