# Generated by Django 2.2.4 on 2019-10-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0002_auto_20191013_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(verbose_name='邮箱'),
        ),
    ]
