# Generated by Django 2.2.10 on 2020-04-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0002_auto_20200405_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yonghu',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
