# Generated by Django 2.0.6 on 2020-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0003_auto_20200218_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='yonghu',
            name='is_auth_new',
            field=models.BooleanField(default=False, verbose_name='是否认证(新系统)'),
        ),
    ]
