# Generated by Django 2.2.4 on 2019-10-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0003_auto_20191013_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
    ]
