# Generated by Django 2.2.4 on 2019-10-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0004_auto_20191013_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人介绍'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
