# Generated by Django 2.2.4 on 2019-10-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0007_auto_20191019_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='昵称'),
        ),
    ]
