# Generated by Django 2.2.4 on 2019-10-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0009_auto_20191019_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, verbose_name='昵称'),
        ),
    ]
