# Generated by Django 2.2.4 on 2019-10-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0011_auto_20191019_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱'), ('email_login', '邮箱登录')], default='register', max_length=30, verbose_name='验证码类型'),
        ),
    ]
