# Generated by Django 2.2.4 on 2019-10-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0012_auto_20191023_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='send_time',
            field=models.DateTimeField(auto_now=True, verbose_name='发送时间'),
        ),
    ]
