# Generated by Django 2.2.13 on 2020-10-05 19:12

from django.db import migrations, models
import django.db.models.deletion
import utils.getImagePath
import utils.uscSystem.getReadAndReplyNumLikes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='类型')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.CreateModel(
            name='Commody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('description', models.TextField(verbose_name='描述信息')),
                ('price', models.FloatField(verbose_name='价格')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('qq', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='QQ号')),
                ('wx', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='微信号')),
                ('phone_number', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='电话号码')),
                ('user', models.CharField(max_length=255, null=True, verbose_name='发表用户')),
                ('platform', models.CharField(max_length=10, null=True, verbose_name='平台')),
                ('is_end', models.BooleanField(default=False, verbose_name='是否结束')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commody', to='transaction.Type')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
            bases=(models.Model, utils.uscSystem.getReadAndReplyNumLikes.GetReadAndReplyAndLikesNum, utils.getImagePath.GetImagePath),
        ),
    ]
