# Generated by Django 2.2.10 on 2020-03-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yonghu', '0004_yonghu_is_auth_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('description', models.TextField(verbose_name='描述信息')),
                ('price', models.FloatField(verbose_name='价格')),
                ('read_num', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('type', models.CharField(max_length=12, verbose_name='类型')),
                ('qq', models.CharField(default='', max_length=15, verbose_name='QQ号')),
                ('wx', models.CharField(default='', max_length=25, verbose_name='微信号')),
                ('phone_number', models.CharField(default='', max_length=11, verbose_name='电话号码')),
                ('replyNum', models.IntegerField(verbose_name='留言数')),
                ('floorNum', models.IntegerField(verbose_name='主楼数')),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commody', to='yonghu.Yonghu')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=128, verbose_name='留言')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_reply', models.BooleanField(default=False, verbose_name='是否是楼中楼')),
                ('floor', models.CharField(default='', max_length=10, verbose_name='第几楼')),
                ('commody', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message', to='transaction.Commody')),
                ('reply_yonghu', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_yonghu', to='yonghu.Yonghu')),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message', to='yonghu.Yonghu')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgPath', models.URLField(verbose_name='图片链接')),
                ('commody', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='imagePath', to='transaction.Commody')),
            ],
        ),
    ]
