# Generated by Django 2.2.10 on 2020-03-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commody',
            name='phone_number',
            field=models.CharField(default='', max_length=11, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='commody',
            name='qq',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='commody',
            name='wx',
            field=models.CharField(default='', max_length=25, null=True, verbose_name='微信号'),
        ),
    ]
