# Generated by Django 2.2.10 on 2020-03-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_yonghu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_message', to='yonghu.Yonghu'),
        ),
    ]
