# Generated by Django 2.2.10 on 2020-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200317_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commody',
            name='floorNum',
            field=models.IntegerField(blank=True, default=0, verbose_name='主楼数'),
        ),
        migrations.AlterField(
            model_name='commody',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='commody',
            name='qq',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='commody',
            name='replyNum',
            field=models.IntegerField(blank=True, default=0, verbose_name='留言数'),
        ),
        migrations.AlterField(
            model_name='commody',
            name='wx',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='微信号'),
        ),
    ]
