# Generated by Django 2.2.10 on 2020-03-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20200317_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
