# Generated by Django 2.2.10 on 2020-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='commody',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='commody',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='是否结束'),
        ),
    ]
