# Generated by Django 2.2.10 on 2020-03-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('yonghu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=128, verbose_name='留言')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='第几楼')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message', to='yonghu.Yonghu')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.CreateModel(
            name='ReplyMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Messages.Message')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_message', to='Messages.Message')),
                ('reply_yonghu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_message', to='yonghu.Yonghu')),
            ],
            options={
                'verbose_name': '留言回复',
                'verbose_name_plural': '留言回复',
            },
            bases=('Messages.message',),
        ),
    ]
