# Generated by Django 2.2.10 on 2020-03-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='floor',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='第几楼'),
        ),
    ]
