# Generated by Django 2.2.10 on 2020-03-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_auto_20200318_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Messages.Message')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
            bases=('Messages.message',),
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='replymessage',
            name='comment',
        ),
    ]
