# Generated by Django 2.2.10 on 2020-03-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0004_auto_20200318_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='floor',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True, verbose_name='第几楼'),
        ),
    ]
