# Generated by Django 2.2.10 on 2020-03-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readAndReplyNum', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePath',
        ),
    ]
