# Generated by Django 2.2.10 on 2020-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readAndReplyNum', '0002_delete_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='readandreplynum',
            name='main_floor_num',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='主楼数'),
        ),
    ]
